import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Main from '../components/Main'
import Navbar from '../components/Navbar'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Footer from '../components/Footer'
import Payments from '../components/Payments'
import Faq from '../components/Faq'
import Contact from '../components/Contact'
export default function Home() {
  return (
    <div >
      <Head>
        <title>Sean | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <!-- Google tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-157001701-2">
</script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-157001701-2');
</script>
      </Head>
      <Navbar />
      <Main />
      <About /> 
      <Skills />
      <Projects />
      <Payments />
      <Faq />
      <Contact />
      <Footer />

    </div>
  )
}
