
import Head from 'next/head'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Payments from '../components/Payments'
import Contact from '../components/Contact'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Sean | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <head>
          
        </head>
      </Head>
      <Navbar />
      <Payments/>
      <Contact />
      <Footer />

    </div>
  )
}
