import Head from 'next/head'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

const team = () => {

  return (
    <>
    <Head>
        <title>Decoded Web | Web development Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar />
    <div id='team' className='py-16 w-full lg:h-screen pt-40 bg-[#f1f1f1] bg-bg_image11 bg-contain bg-center bg-no-repeat bg-fixed'>
      <div className='max-w-[1240px] p-2 py-20 mt-20 mx-auto flex flex-col justify-center bg-[#c7b7baf7] border-double border-2 rounded-sm border-gray-800' >
        <div className='uppercase text-xl tracking-widest text-[#ce3636]'>
          <h2></h2>
          <hr/>
          </div>
          <h2 className='py-4 mt-4 text-[#638d5e] bg-[#1a1a1a] align-left w-full rounded-tr-border-2 px-10 rounded-br-[10px]  rounded-tl-[10px]'>COMING SOON</h2>
      
        </div>
    </div>
    <Footer />
    </>
  );
};

export default team;
